//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StategyCricket.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int BattingAttribute { get; set; }
        public int BowlingAttribute { get; set; }
        public string Team { get; set; }
        public string Country { get; set; }
    }
}
