//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StategyCricket.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayersData
    {
        public int ID { get; set; }
        public Nullable<int> Runs { get; set; }
        public Nullable<int> BallsFaced { get; set; }
        public Nullable<int> Wickets { get; set; }
        public Nullable<int> Overs { get; set; }
        public Nullable<int> HighestScore { get; set; }
        public string BestBowling { get; set; }
        public Nullable<int> BattingInnings { get; set; }
        public Nullable<int> BowlingInnings { get; set; }
    }
}
